"""add preparation table

Revision ID: 6dbfe5d7afe9
Revises:
Create Date: 2025-11-27 01:57:42.217216

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dbfe5d7afe9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_pagamento",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("posicao_preparacao", sa.Integer(), nullable=True),
        sa.Column("tempo_de_preparacao", sa.Integer(), nullable=False),
        sa.Column("estimativa_de_pronto", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "st_preparacao",
            sa.Enum(
                "RECEIVED",
                "IN_PREPARATION",
                "READY",
                "COMPLETED",
                name="preparationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("dt_inclusao", sa.TIMESTAMP(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_tb_pagamento_st_preparacao"),
        "tb_pagamento",
        ["st_preparacao"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tb_pagamento_st_preparacao"), table_name="tb_pagamento")
    op.drop_table("tb_pagamento")
    # ### end Alembic commands ###
